// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// portMap
NumericVector portMap(IntegerVector xpos, IntegerVector ypos, NumericVector xmap);
RcppExport SEXP bulkPop_portMap(SEXP xposSEXP, SEXP yposSEXP, SEXP xmapSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< IntegerVector >::type xpos(xposSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type ypos(yposSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type xmap(xmapSEXP);
    __result = Rcpp::wrap(portMap(xpos, ypos, xmap));
    return __result;
END_RCPP
}
