# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

portMap <- function(xpos, ypos, xmap) {
    .Call('bulkPop_portMap', PACKAGE = 'bulkPop', xpos, ypos, xmap)
}

summarizePop <- function(hapPop, maxLength) {
    .Call('bulkPop_summarizePop', PACKAGE = 'bulkPop', hapPop, maxLength)
}

